version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun_vpn
    cap_add:
      - NET_ADMIN
    ports:
      - 8080:8080
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=Kj8sVQCfZgH9yUc4hn9HgUqa
      - OPENVPN_PASSWORD=UseS16K22rJo1U28fYSKAJz1
      - SERVER_REGIONS=Canada
