http:
  routers:
    forwarded-wireguard:
      rule: "Host(`wireguard.local.sowt.ca`)"
      service: wireguard-remote-service
    forwarded-qbit:
      rule: "Host(`qbits.local.sowt.ca`)"
      service: qbit-remote-service
    forwarded-jenkins:
      rule: "Host(`jenkins.local.sowt.ca`)"
      service: jenkins-remote-service
    

  services:
    wireguard-remote-service:
      loadBalancer:
        servers:
          - url: "http://10.0.0.172:51821"  # Replace with actual remote host and port
    qbit-remote-service:
      loadBalancer:
        servers:
          - url: "http://10.0.0.172:8081"  # Replace with actual remote host and port
    jenkins-remote-service:
      loadBalancer:
        servers:
          - url: "http://10.0.0.172:8080"  # Replace with actual remote host and port
             
https:
  routers:
    forwarded-portainer:
      rule: "Host(`portainer.local.sowt.ca`)"
      service: portainer-remote-service
  services:
    portainer-remote-service:
      loadBalancer:
        servers:
          - url: "https://10.0.0.172:9443"  # Replace with actual remote host and port
      scheme: "https"