services:
  portainer_agent:
    image: portainer/agent
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
    networks:
      - portainer_agent_network
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

networks:
  portainer_agent_network:
    external: true
