version: "2.1"
volumes:
  torrents:
    name: torrents
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: container:gluetun_vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/NewYork
      - WEBUI_PORT=8080
      - WEBUI_USERNAME=admin  # Replace 'your_username' with the desired username
      - WEBUI_PASSWORD=admin123  # Replace 'your_password' with the desired password
    volumes:
      - /volume1/Plex_Media/torrents:/downloads
    restart: unless-stopped
