version: "3.8"
services:
  portainer:
    image: portainer/portainer-ce:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    ports:
      - target: 8000
        published: 8000
        mode: host
      - target: 9443
        published: 9443
        mode: host
    networks:
      - portainer_agent_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

networks:
  portainer_agent_network:
    external: true

volumes:
  portainer_data: {}
