name: Trigger Jenkins Build

on:
  push:
    branches:
      - main  # Adjust to your branch

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Call Jenkins Webhook
        run: |
          curl -X POST \
                -H "Content-Type: application/json" \
                -H "X-GitHub-Event: push" \
                --data '{"ref": "${{ github.ref }}", "repository": {"full_name": "${{ github.repository }}"}}' \
                "${{ secrets.JENKINS_WEBHOOK }}"
